In [64]:
words = open('names.txt','r').read().splitlines()

In [66]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [68]:
len(words)

32033

In [70]:
min(len(w) for w in words) #words안에 있는 것 중에 가장 작은 알파벳 갯수

2

In [72]:
max(len(w) for w in words)

15

In [74]:
for w in words[:1]:
    for ch1, ch2 in zip(w,w[1:]):
        print(ch1, ch2) #한 번에 두 문자씩, 단어 사이를 밀어서 반복할 것이다....?

e m
m m
m a


In [76]:
w

'emma'

In [78]:
w[1:]

'mma'

In [80]:
for w in words[:3]:
    chs = ['<S>']+list(w)+['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        print(ch1, ch2)

<S> e
e m
m m
m a
a <E>
<S> o
o l
l i
i v
v i
i a
a <E>
<S> a
a v
v a
a <E>


In [82]:
b={}
for w in words[:3]:
    chs = ['<S>']+list(w)+['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        bigram=(ch1, ch2)
        b[bigram] =b.get(bigram,0)+1    
        print(ch1, ch2)

<S> e
e m
m m
m a
a <E>
<S> o
o l
l i
i v
v i
i a
a <E>
<S> a
a v
v a
a <E>


In [84]:
b #a로 끝나는 횟수가 3번 있었다.

{('<S>', 'e'): 1,
 ('e', 'm'): 1,
 ('m', 'm'): 1,
 ('m', 'a'): 1,
 ('a', '<E>'): 3,
 ('<S>', 'o'): 1,
 ('o', 'l'): 1,
 ('l', 'i'): 1,
 ('i', 'v'): 1,
 ('v', 'i'): 1,
 ('i', 'a'): 1,
 ('<S>', 'a'): 1,
 ('a', 'v'): 1,
 ('v', 'a'): 1}

In [86]:
b={}
for w in words:
    chs = ['<S>']+list(w)+['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        bigram=(ch1, ch2)
        b[bigram] =b.get(bigram,0)+1

In [88]:
b

{('<S>', 'e'): 1531,
 ('e', 'm'): 769,
 ('m', 'm'): 168,
 ('m', 'a'): 2590,
 ('a', '<E>'): 6640,
 ('<S>', 'o'): 394,
 ('o', 'l'): 619,
 ('l', 'i'): 2480,
 ('i', 'v'): 269,
 ('v', 'i'): 911,
 ('i', 'a'): 2445,
 ('<S>', 'a'): 4410,
 ('a', 'v'): 834,
 ('v', 'a'): 642,
 ('<S>', 'i'): 591,
 ('i', 's'): 1316,
 ('s', 'a'): 1201,
 ('a', 'b'): 541,
 ('b', 'e'): 655,
 ('e', 'l'): 3248,
 ('l', 'l'): 1345,
 ('l', 'a'): 2623,
 ('<S>', 's'): 2055,
 ('s', 'o'): 531,
 ('o', 'p'): 95,
 ('p', 'h'): 204,
 ('h', 'i'): 729,
 ('<S>', 'c'): 1542,
 ('c', 'h'): 664,
 ('h', 'a'): 2244,
 ('a', 'r'): 3264,
 ('r', 'l'): 413,
 ('l', 'o'): 692,
 ('o', 't'): 118,
 ('t', 't'): 374,
 ('t', 'e'): 716,
 ('e', '<E>'): 3983,
 ('<S>', 'm'): 2538,
 ('m', 'i'): 1256,
 ('a', 'm'): 1634,
 ('m', 'e'): 818,
 ('<S>', 'h'): 874,
 ('r', 'p'): 14,
 ('p', 'e'): 197,
 ('e', 'r'): 1958,
 ('r', '<E>'): 1377,
 ('e', 'v'): 463,
 ('v', 'e'): 568,
 ('l', 'y'): 1588,
 ('y', 'n'): 1826,
 ('n', '<E>'): 6763,
 ('b', 'i'): 217,
 ('i', 'g'): 428,


In [90]:
sorted(b.items(), key = lambda kv: kv[1]) #value값을 오름차순으로 나열하기

[(('q', 'r'), 1),
 (('d', 'z'), 1),
 (('p', 'j'), 1),
 (('q', 'l'), 1),
 (('p', 'f'), 1),
 (('q', 'e'), 1),
 (('b', 'c'), 1),
 (('c', 'd'), 1),
 (('m', 'f'), 1),
 (('p', 'n'), 1),
 (('w', 'b'), 1),
 (('p', 'c'), 1),
 (('h', 'p'), 1),
 (('f', 'h'), 1),
 (('b', 'j'), 1),
 (('f', 'g'), 1),
 (('z', 'g'), 1),
 (('c', 'p'), 1),
 (('p', 'k'), 1),
 (('p', 'm'), 1),
 (('x', 'n'), 1),
 (('s', 'q'), 1),
 (('k', 'f'), 1),
 (('m', 'k'), 1),
 (('x', 'h'), 1),
 (('g', 'f'), 1),
 (('v', 'b'), 1),
 (('j', 'p'), 1),
 (('g', 'z'), 1),
 (('v', 'd'), 1),
 (('d', 'b'), 1),
 (('v', 'h'), 1),
 (('h', 'h'), 1),
 (('g', 'v'), 1),
 (('d', 'q'), 1),
 (('x', 'b'), 1),
 (('w', 'z'), 1),
 (('h', 'q'), 1),
 (('j', 'b'), 1),
 (('x', 'm'), 1),
 (('w', 'g'), 1),
 (('t', 'b'), 1),
 (('z', 'x'), 1),
 (('p', 'b'), 2),
 (('t', 'g'), 2),
 (('q', 's'), 2),
 (('t', 'x'), 2),
 (('f', 'k'), 2),
 (('b', 't'), 2),
 (('j', 'n'), 2),
 (('k', 'c'), 2),
 (('z', 'k'), 2),
 (('s', 'j'), 2),
 (('s', 'f'), 2),
 (('z', 'j'), 2),
 (('n', 'q

In [92]:
import torch

In [94]:
!pip install torch

In [95]:
#array의 index를 이용하는방법
N = torch.zeros((27,27), dtype=torch.int32) # 횟수를 표시하기 위해서 dtype=torch.int32 사용 #알파벳이 26개고 special 알파벳이 2개 더 있어서 28개임

In [96]:
sorted(list(set(''.join(words)))) #set은 중복을 허용하지 않는다

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [97]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i for i,s in enumerate(chars)}

In [98]:
itos = {i:s for s,i in stoi.items()} #stoi의 역버전
itos

{0: 'a',
 1: 'b',
 2: 'c',
 3: 'd',
 4: 'e',
 5: 'f',
 6: 'g',
 7: 'h',
 8: 'i',
 9: 'j',
 10: 'k',
 11: 'l',
 12: 'm',
 13: 'n',
 14: 'o',
 15: 'p',
 16: 'q',
 17: 'r',
 18: 's',
 19: 't',
 20: 'u',
 21: 'v',
 22: 'w',
 23: 'x',
 24: 'y',
 25: 'z'}

In [99]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}

for w in words:
    chs = ['.']+list(w)+['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        N[ix1, ix2]+=1

In [100]:
N[0, :].shape

torch.Size([27])

In [101]:
# 횟수말고 샘플의 확률을 구하고자함
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [102]:
g = torch.Generator().manual_seed(2147483647)

ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item() #index뽑아내기
itos[ix]

'j'

In [103]:
p.sum()

tensor(1.)

In [104]:
g = torch.Generator().manual_seed(2147483647) #random seed를 정해주었다
p = torch.rand(3, generator =g) #같은generator를 사용
p = p/p.sum()
p
#0일 확률 약 60퍼, 1일 확률 약 30퍼, 2일 확률 약 9퍼

tensor([0.6064, 0.3033, 0.0903])

In [105]:
torch.multinomial(p, num_samples=100, replacement=True, generator=g) #replacement = true로 설정하여 샘플링될 때마다 다시 선택될 수 있도록 한다.
# 결정론적인 결과를 얻는다

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0,
        0, 1, 1, 1])

In [106]:
g = torch.Generator().manual_seed(2147483647)

out=[]
ix = 0
while True : 
    p = N[ix].float()
    p=p/p.sum()
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix == 0 :
        break
print(''.join(out))
#반복문을 작성해서 이름을 구함

junide.


In [107]:
#6
#각 행을 반복할 때마다 불필요한 연산을 수행하는 비효율적인 과정을 개선하고자 한다
#각 행이 1로 정규화된 확률 분포인 행렬 P를 준비하고, 이를 사용하여 연산하는 것이 목표

In [123]:
#27,27
#27, 1
P.sum(1,keepdim=True).shape

torch.Size([27, 1])

In [121]:
P = (N+1).float()
P=P/P.sum(1, keepdim=True)

In [125]:
g = torch.Generator().manual_seed(2147483647)
for i in range(5):

    out=[]
    ix=0
    while True : 
        p=P[ix]
        ix=torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out.append(itos[ix])
        if ix==0:
            break
    print(''.join(out))

junide.
janasah.
p.
cony.
a.


In [127]:
#GOAL : maximize likelihood of the data w.r.t. model parameters(statistical modeling)
#equivalent to maximizing the log likelihood (because log is monotonic)
#equivalent to minimizing the negative log likelihood
#equivalent to minimizing the average negative log likelihood

# log(a*b*c) = log(a)+ lob(b)+ log(c)
# 

In [129]:
##7 모델 평가하기?
log_likelihood=0.0
n=0

for w in words[:3]:
    chs = ['.']+list(w)+['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood+=logprob
        n+=1
        print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')

print(f'{log_likelihood=}')
nll=-log_likelihood
print(f'{nll=}')
print(f'{nll/n}')

.e: 0.0478 -3.0410
em: 0.0377 -3.2793
mm: 0.0253 -3.6753
ma: 0.3885 -0.9454
a.: 0.1958 -1.6305
.o: 0.0123 -4.3965
ol: 0.0779 -2.5526
li: 0.1774 -1.7293
iv: 0.0152 -4.1845
vi: 0.3508 -1.0476
ia: 0.1380 -1.9807
a.: 0.1958 -1.6305
.a: 0.1376 -1.9835
av: 0.0246 -3.7041
va: 0.2473 -1.3971
a.: 0.1958 -1.6305
log_likelihood=tensor(-38.8086)
nll=tensor(38.8086)
2.4255354404449463


In [131]:
# 8
#P = (N+1).float()을 통해 infinite값을 없애줌

In [133]:
#9
#creat the training set of bigrams (x,y)
xs, ys = [],[]

for w in words[:1]:
    chs = ['.']+list(w)+['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        print(ch1, ch2)
        xs.append(ix1)
        ys.append(ix2)

xs=torch.tensor(xs)
ys=torch.tensor(ys)

. e
e m
m m
m a
a .


In [207]:
# summary ------------------------->

In [135]:
xs

tensor([ 0,  5, 13, 13,  1])

In [137]:
ys

tensor([ 5, 13, 13,  1,  0])

In [239]:
# randomly initaialize 27 neurons' weights. each neuron receives 27 inputs
g= torch.Generator().manual_seed(2146483647)
W=torch.randn((27,27), generator=g, requires_grad=True)

In [225]:
#forward pass
xenc = F.one_hot(xs, num_classes=27).float() #input to the network: one-hot encoding
logits = xenc @ W #predict log-counts
counts = logits.exp() #counts, equivalent to N
probs = counts / counts.sum(1, keepdims=True) #probabilities for next character
#btw: the last 2 lines here are together called a 'softmax'

In [227]:
probs.shape

torch.Size([5, 27])

In [213]:
probs.shape

torch.Size([5, 27])

In [217]:
nlls = torch.zeros(5)
for i in range(5):
    # i-th bigram
    x=xs[i].item() #input character index
    y=ys[i].item() #label character index
    print('-------')
    print(f'bigram example {i+1}: {itos[x]}{itos[y]} (indexes {x},{y})')
    print('input to the nerual net: ', x)
    print('output probabilities from teh neural net: ', probs[i])
    print('label (actual next character): ',y)
    p = probs[i,y]
    print('probability assigned by the net to the correct character: ', p.item())
    logp = torch.log(p)
    print('log likelihood: ', logp.item())
    nll = -logp
    print("negative log likelihood: ", nll.item())
    nlls[i] = nll

print('===========')
print('average negative log likelihood, i.e. loss= ', nlls.mean().item())

-------
bigram example 1: .e (indexes 0,5)
input to the nerual net:  0
output probabilities from teh neural net:  tensor([0.0182, 0.0018, 0.0066, 0.0628, 0.1830, 0.2143, 0.0111, 0.0280, 0.0194,
        0.0108, 0.0139, 0.0046, 0.0088, 0.0035, 0.0739, 0.0720, 0.0355, 0.0929,
        0.0287, 0.0049, 0.0298, 0.0165, 0.0117, 0.0064, 0.0067, 0.0142, 0.0199])
label (actual next character):  5
probability assigned by the net to the correct character:  0.21434566378593445
log likelihood:  -1.5401653051376343
negative log likelihood:  1.5401653051376343
-------
bigram example 2: em (indexes 5,13)
input to the nerual net:  5
output probabilities from teh neural net:  tensor([0.0018, 0.0934, 0.0233, 0.0065, 0.1139, 0.0414, 0.0154, 0.0336, 0.0339,
        0.0196, 0.0268, 0.0028, 0.0199, 0.0588, 0.0801, 0.0388, 0.0405, 0.1059,
        0.0145, 0.0148, 0.0515, 0.0034, 0.1135, 0.0074, 0.0052, 0.0224, 0.0108])
label (actual next character):  13
probability assigned by the net to the correct character:  

In [219]:
#---- !!! OPIMIZATION !!! yay ------------------

In [221]:
xs

tensor([ 0,  5, 13, 13,  1])

In [223]:
ys

tensor([ 5, 13, 13,  1,  0])

In [ ]:
probs[0,5], probs[1,]

In [139]:
xs.dtype

torch.int64

In [141]:
##11
import torch.nn.functional as F
xenc = F.one_hot(xs, num_classes=27)
xenc

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]])

In [179]:
xenc.dtype

torch.float32

In [177]:
#12
W = torch.randn((27,27)) #noraml distribution
xenc @ W

tensor([[-1.1454e+00,  5.4566e-01, -1.1362e+00, -8.0811e-01,  4.0483e-01,
          1.1335e+00, -8.9263e-01, -1.1011e+00, -8.6170e-01,  8.2131e-02,
          3.8419e-02, -1.2614e+00,  1.3482e+00, -1.5755e-01, -2.3979e+00,
          1.4799e+00, -6.1630e-01, -3.5805e-01,  1.1796e-01, -4.0798e-01,
         -1.6213e+00,  3.5593e-01, -6.3289e-01,  9.6079e-01, -4.1943e-01,
          1.2356e+00,  5.8057e-01],
        [ 2.9794e-01, -2.6136e-01,  1.2822e+00, -2.9077e-01, -1.7130e-01,
         -1.3859e+00, -1.9539e+00, -1.0558e+00,  2.8990e-01, -3.8450e-01,
          3.3800e-01, -1.3654e+00, -9.3800e-01, -6.5997e-01,  1.9345e-01,
          3.2789e-01, -4.7592e-02,  1.2061e+00, -1.2437e+00, -2.0147e+00,
         -5.3138e-01,  1.1023e+00, -2.6409e-01, -2.1910e-01, -4.8327e-01,
          9.0257e-02, -1.6985e+00],
        [ 2.0129e-01, -4.3835e-01,  1.4678e-01, -6.3304e-02, -8.0186e-01,
          2.6562e+00,  7.8826e-01,  1.4633e+00,  6.9332e-01, -1.7695e-02,
          1.0603e+00, -5.7038e-01, -1.42

In [183]:
# (5, 27) @ (27,1) -> (5,27)
(xenc@W)[3,13]

tensor(-1.7784)

In [187]:
W[:,13]

tensor([-0.1576, -0.9020, -0.5247,  0.2243, -2.0184, -0.6600, -0.6150, -1.7270,
        -0.2495,  0.6230, -0.2850, -0.1064, -0.6751, -1.7784,  1.1678,  0.6961,
        -0.9902,  1.5733, -0.5616, -1.0778,  0.4422,  0.7427,  1.0466,  1.1822,
         1.0113, -0.2529,  0.1704])

In [197]:
#13
(xenc@W).exp() #양수가 됌
logits = xenc @ W #log-counts
counts = logits.exp() #equvialent N
probs = counts / counts.sum(1,keepdims=True)
probs

tensor([[0.0094, 0.0510, 0.0095, 0.0132, 0.0443, 0.0917, 0.0121, 0.0098, 0.0125,
         0.0321, 0.0307, 0.0084, 0.1137, 0.0252, 0.0027, 0.1297, 0.0159, 0.0206,
         0.0332, 0.0196, 0.0058, 0.0422, 0.0157, 0.0772, 0.0194, 0.1016, 0.0528],
        [0.0499, 0.0285, 0.1334, 0.0277, 0.0312, 0.0093, 0.0052, 0.0129, 0.0495,
         0.0252, 0.0519, 0.0094, 0.0145, 0.0191, 0.0449, 0.0514, 0.0353, 0.1236,
         0.0107, 0.0049, 0.0218, 0.1115, 0.0284, 0.0297, 0.0228, 0.0405, 0.0068],
        [0.0277, 0.0146, 0.0262, 0.0212, 0.0101, 0.3223, 0.0498, 0.0978, 0.0453,
         0.0222, 0.0653, 0.0128, 0.0054, 0.0038, 0.0104, 0.0174, 0.0504, 0.0286,
         0.0039, 0.0143, 0.0091, 0.0073, 0.0418, 0.0221, 0.0027, 0.0220, 0.0454],
        [0.0277, 0.0146, 0.0262, 0.0212, 0.0101, 0.3223, 0.0498, 0.0978, 0.0453,
         0.0222, 0.0653, 0.0128, 0.0054, 0.0038, 0.0104, 0.0174, 0.0504, 0.0286,
         0.0039, 0.0143, 0.0091, 0.0073, 0.0418, 0.0221, 0.0027, 0.0220, 0.0454],
        [0.0193, 0.0455,

In [201]:
probs.shape

torch.Size([5, 27])

In [203]:
probs[0].sum()

tensor(1.)

In [205]:
probs[0]

tensor([0.0094, 0.0510, 0.0095, 0.0132, 0.0443, 0.0917, 0.0121, 0.0098, 0.0125,
        0.0321, 0.0307, 0.0084, 0.1137, 0.0252, 0.0027, 0.1297, 0.0159, 0.0206,
        0.0332, 0.0196, 0.0058, 0.0422, 0.0157, 0.0772, 0.0194, 0.1016, 0.0528])

In [229]:
#14
probs[0,5], probs[1,13], probs[2,13], probs[3,1], probs[4,0]

(tensor(0.2143),
 tensor(0.0588),
 tensor(0.0216),
 tensor(0.0336),
 tensor(0.0059))

In [243]:
torch.arange(5)
probs[torch.arange(5), ys] #ys로 인덱싱함

tensor([0.2143, 0.0588, 0.0216, 0.0336, 0.0059], grad_fn=<IndexBackward0>)

In [233]:
loss = -probs[torch.arange(5), ys].log().mean()
loss

tensor(3.3472)

In [241]:
#forward pass
xenc = F.one_hot(xs, num_classes=27).float() #input to the network: one-hot encoding
logits = xenc @ W #predict log-counts
counts = logits.exp() #counts, equivalent to N
probs = counts / counts.sum(1, keepdims=True) #probabilities for next character
loss =- probs[torch.arange(5), ys].log().mean()

In [261]:
# creat the dataset
xs, ys = [], []
for w in words[:1]:
    chs = ['.']+ list(w)+['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        xs.append(ix1)
        ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples: ', num)

#initialize the 'network'
g=torch.Generator().manual_seed(2147483647)
W= torch.randn((27,27), generator=g, requires_grad=True)

number of examples:  5


In [263]:
#gradient descent
for k in range(10):

    #forward pass
    xenc = F.one_hot(xs, num_classes = 27).float() #input to the network: one-hot encoding
    logits = xenc@W #predict log-counts
    counts = logits.exp() #counts, equivalent to N
    probs = counts / counts.sum(1, keepdims=True) #probabilities for next character
    loss = -probs[torch.arange(num), ys].log().mean()
    print(loss.item())

    #backward pass
    W.grad = None #set to zero the gradient
    
    #update
    W.data += -0.1 * W.grad

3.7693049907684326


TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'